services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: ecommerce-linktic
        working_dir: /var/www
        ports:
            - '8000:8000'
        volumes:
            - '.:/var/www'
            # - ./public/storage:/var/www/public/storage
        networks:
            - laravel-net
        depends_on:
            - mysql
    mysql:
        image: 'mysql:8.0'
        container_name: mysql-db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ecommerce_linktic
            MYSQL_USER: linktic
            MYSQL_PASSWORD: linktic
        ports:
            - '3306:3306'
        volumes:
           - sail-mysql:/var/lib/mysql
        networks:
            - laravel-net
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: root
        ports:
            - '8080:80'
        networks:
            - laravel-net
networks:
    laravel-net:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
